#!/bin/bash
. /usr/share/eole/FonctionsEoleNg
. /usr/bin/ParseDico

if [ $active_nufw == 'oui' ] && [ ! $nuauth_tls_cert = '' ]; then
        EchoGras "*** Validité des certificats Nuauth"
	TestCerts $nuauth_tls_cert 10 "certificat expiré"
	TestCerts /etc/nufw/certs/nufw-eole.crt 10 "certificat expiré"
	echo
fi
exit 0
