#!/bin/bash

. /etc/eole/containers.conf

touch "$container_path_proxy/etc/squid/domaines_noauth_user"
touch "$container_path_proxy/etc/squid/domaines_nocache_user"
touch "$container_path_proxy/etc/squid/src_noauth_user"
touch "$container_path_proxy/etc/squid/src_nocache_user"
touch "$container_path_proxy/etc/squid/domaines_noauth_acad"
touch "$container_path_proxy/etc/squid/domaines_nocache_acad"
touch "$container_path_proxy/etc/squid/src_noauth_acad"
touch "$container_path_proxy/etc/squid/src_nocache_acad"

# FIXME 2.3
if [ ! -f "$container_path_proxy/etc/squid/src_noauth" ];then
    echo "127.0.0.1" > "$container_path_proxy/etc/squid/src_noauth"
fi
if [ ! -f "$container_path_proxy/etc/squid/src_nocache" ];then
    echo "127.0.0.1" > "$container_path_proxy/etc/squid/src_nocache"
fi

exit 0
