#!/bin/bash

# pre-instance pour Amon

# accès Ead aux log de squid
chmod o+rx /var/log/squid
touch /var/log/squid/access.log
chown proxy.proxy /var/log/squid/access.log
chmod o+r  /var/log/squid/access.log

# nouveaux fichiers squid
touch "/etc/squid/domaines_noauth_user"
touch "/etc/squid/domaines_nocache_user"
touch "/etc/squid/src_noauth_user"
touch "/etc/squid/src_nocache_user"

# FIX pour nuauth
chmod 600 /etc/nufw/certs/nuauth-key.pem

# Creation d'un utilisateur amon2 pour la configuration de la zone 2
id amon &>/dev/null
if [ $? -eq 0 ]
then
  id amon2 &>/dev/null
  if [ $? -ne 0 ]
  then
        echo ""
        echo "############################################################"
        echo "#     Création d'un deuxième compte local (amon2)     #"
        echo "############################################################"
	echo "Voulez-vous ajouter cet utilisateur ? 
	read Rep
	if [ "$Rep" = "oui" -o "$Rep" = "o" -o "$Rep" = "O" ]
	then
        	useradd 'amon2'
	fi
        res=1
        while [ $res -ne 0 ]
        do
                passwd amon2
                res=$?
        done
	echo
  fi
fi
exit 0
