# -*- coding: UTF-8 -*-
"""
Surveillance du service DNS (bind9)
"""

from zephir.monitor.agents.services import TCPServices

test = '%s:53' % DICO.get('adresse_ip_conteneur_dns', 'localhost')
data = {test: "Serveur de noms (DNS)"}
AGENTS.append(TCPServices('dns', data, period=20,
                          description='Etat du serveur de noms (DNS)'))
