# -*- coding: UTF-8 -*-
"""
Surveillance du service Dansguardian (eth0 ou conteneur)
"""

from zephir.monitor.agents.services import TCPServices
#from zephir.monitor.agents.services import PIDService

if DICO['nombre_interfaces'] > 2:
    if DICO['adresse_ip_proxy'] == '127.0.0.1':
        # sans conteneur
        test = '%s:3128' % DICO['adresse_ip_eth2']
        data = {test:"Filtrage sur %s" % DICO["nom_machine_eth2"]}
        AGENTS.append(TCPServices('dans2', data, period=115,
                      description="Etat du service dansguardian sur eth2"))
#    else:
#        # avec conteneurs
#        # FIXME : le test suivant devrait être fait dans le conteneur !
#        #test = '%s:3128' % DICO['adresse_ip_eth2_proxy_link']
