#!/bin/bash
###########################################################
# gen_dns
# generation de named.conf et des fichiers de zone pour bind
############################################################

# appel des fonctions Eole
. ParseDico
. /etc/eole/containers.conf

## Correction bug si nom_domaine_local == local
if [ -e "$container_path_dns/etc/bind/db.local" ]
then
	rm -f "$container_path_dns/etc/bind/db.local"
fi
##
NAMEDCONF=$container_path_dns/etc/bind/named.conf

declare -i I Max nb_int
cd $container_path_dns/etc/bind
if [ "$container_path_dns" = "" ]; then
DOMAINNAME=$nom_machine.$nom_domaine_local
else
cname=`echo $container_path_dns|awk -F/ '{ print $(NF-1) }'`
DOMAINNAME=$cname.$nom_domaine_local
fi
Cmd="/usr/share/eole/h2n -h $nom_machine -d $nom_domaine_local -s $DOMAINNAME"
Max=`expr $nombre_interfaces - 1`
I=0
while [ $I -le $Max ]
do
	Master=dns_master_eth${I}
	if [ ${!Master}  == "oui" ]
	then
	   Network=adresse_network_eth${I}
	   Netmask=adresse_netmask_eth${I}
           Cmd=$Cmd" -n ${!Network}:${!Netmask} "
	fi
	I=$I+1
done

Cmd=$Cmd" -M -v 8 -y -b $NAMEDCONF"

#AmonEcole 2.2
#if [ ! $adresse_network_dmz = "" ]
#then
#        Cmd=$Cmd" -n ${adresse_network_dmz}:${adresse_netmask_dmz} "
#fi

$Cmd
cp -f "$container_path_dns/etc/bind/db.root" "$container_path_dns/etc/bind/db.cache"
exit 0
