#!/bin/bash

# utilisateur et groupe : nufwguest
if ! getent group nufwguest >/dev/null; then
        addgroup --gid 253 nufwguest
fi

if ! getent passwd nufwguest >/dev/null; then
        useradd -u 253 -g 253 -s /dev/null nufwguest
fi

# droit pour ces certificats nufw/nuauth
if [ "$activer_nufw" == "oui" ]
then
        [ ! "$nuauth_tls_cacert" == "none" ] && chown root:nuauth $nuauth_tls_cacert && chmod 440 $nuauth_tls_cacert
        [ ! "$nuauth_tls_cert" == "none" ] && chown root:nuauth $nuauth_tls_cert && chmod 440 $nuauth_tls_cert
        [ ! "$nuauth_tls_key" == "none" ] && chown root:nuauth $nuauth_tls_key && chmod 440 $nuauth_tls_key
fi

exit 0
