#!/bin/bash
. /usr/bin/ParseDico

# Dans le cadre d'Amon, c'est le service rvp qui gère ipsec
if [ -L /etc/rc3.d/S20ipsec ]
then
        update-rc.d -f ipsec remove >/dev/null
fi

if [ "$install_rvp" = "non" ]
then
    # ipsec est inutile (#1937)
    /etc/init.d/ipsec stop &>/dev/null
elif [ "$1" = "instance" -a ! -e /etc/ipsec.d/ipsec.db ]
then
    ## Mise en place du VPN ##
    echo
    . /usr/share/eole/FonctionsEoleNg
    Question_ouinon "Voulez-vous configurer le Réseau Virtuel Privé maintenant ?" "non"
    if [ $? -eq 0 ];then
        /usr/share/eole/active_rvp init
    fi
    echo
fi

exit 0
