#!/bin/bash
#
# chkconfig: 2345 85 15
# description: l7filter is a program which detect and prevent some protocols
# processname: l7filter
# pidfile: /var/run/l7filter.pid


RETVAL=0

. /lib/lsb/init-functions

module="xt_layer7"
protocol="bittorrent edonkey"

start() {
	log_begin_msg "Starting l7filter"
	/sbin/iptables -L -n |grep l7proto >/dev/null
	if [ $? == "0" ]
	then
		for i in $protocol; do
			/sbin/iptables -t mangle -D POSTROUTING -m layer7 --l7dir /etc/l7-protocols/protocols --l7proto $i
			/sbin/iptables -D FORWARD -m limit --limit 12/min -m layer7 --l7proto $i -j LOG --log-prefix "L7FILTER-$i-LOG"
			/sbin/iptables -D FORWARD -m layer7 --l7dir /etc/l7-protocols/protocols --l7proto $i -j DROP
			done
		/sbin/iptables -D FORWARD -p udp --dport 123 -j ACCEPT
		/sbin/iptables -D FORWARD -p udp --sport 123 -j ACCEPT
		echo
		rm -f /var/lock/layer7
	fi
	for i in $protocol; do
	/sbin/iptables -t mangle -A POSTROUTING -m layer7 --l7dir /etc/l7-protocols/protocols --l7proto $i
	/sbin/iptables -I FORWARD 2 -m limit --limit 12/min -m layer7 --l7proto $i -j LOG --log-prefix "L7FILTER-$i-LOG"
	/sbin/iptables -I FORWARD 3 -m layer7 --l7dir /etc/l7-protocols/protocols --l7proto $i -j DROP
	done
	/sbin/iptables -I FORWARD 1 -p udp --dport 123 -j ACCEPT
	/sbin/iptables -I FORWARD 1 -p udp --sport 123 -j ACCEPT
	RETVAL=$?
	log_end_msg $RETVAL
	[ $RETVAL -eq 0 ] && touch /var/lock/layer7
	return $RETVAL

}

stop() {
	log_begin_msg "Stop l7filter"
	for i in $protocol; do
	/sbin/iptables -t mangle -D POSTROUTING -m layer7 --l7dir /etc/l7-protocols/protocols --l7proto $i
	/sbin/iptables -D FORWARD -m limit --limit 12/min -m layer7 --l7proto $i -j LOG --log-prefix "L7FILTER-$i-LOG"
	/sbin/iptables -D FORWARD -m layer7 --l7dir /etc/l7-protocols/protocols --l7proto $i -j DROP
	done
	%for %%ntp_iter in %%serveur_ntp
	/sbin/iptables -D FORWARD -p udp --dport 123 -j ACCEPT
	/sbin/iptables -D FORWARD -p udp --sport 123 -j ACCEPT
	%end for
	RETVAL=$?
	log_end_msg $RETVAL
	echo
	[ $RETVAL -eq 0 ] && rm -f /var/lock/layer7
	return $RETVAL
}

case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  restart|reload)
	/sbin/iptables -L -n |grep l7 >/dev/null
	if [ $? == "0" ]
	then
        	stop
	fi
        start
        RETVAL=$?
        ;;
  condrestart)
        if [ -f /var/lock/layer7 ]; then
            stop
            start
            RETVAL=$?
        fi
        ;;
  status)
  	/sbin/iptables -L -n |grep "layer7"
        RETVAL=$?
        ;;
  *)
        gprintf "Usage: %s {start|stop|restart|condrestart|status}\n" "$0"
        exit 1
esac

exit $RETVAL
