#!/bin/bash
. /usr/bin/ParseDico
if [ "$1" = "instance" ];then
    #enregistrement au domaine dans le cas du NTLM/KERBEROS
    if [ "$type_squid_auth" = "NTLM/KERBEROS" -a "$activer_squid_auth" = "oui" ]; then
        # FIXME : tester si l'enregistrement n'est pas déjà fait et OK
        /usr/share/eole/enregistrement_domaine.sh
    fi
    echo
    echo "Voulez-vous mettre à jour les bases de filtrage maintenant ? (oui/non)"
    echo -n "[non] : "
    read Rep
    if [ "$Rep" = "oui" -o "$Rep" = "o" -o "$Rep" = "O" ]
    then
    	/usr/share/eole/Maj-blacklist.sh
    fi
    echo
fi
exit 0
