#!/bin/bash
if [ "$1" = "instance" ];then
    echo
    echo "Voulez-vous mettre à jour les bases de filtrage maintenant ? (oui/non)"
    echo -n "[non] : "
    read Rep
    if [ "$Rep" = "oui" -o "$Rep" = "o" -o "$Rep" = "O" ]
    then
    	/usr/share/eole/Maj-blacklist.sh
    fi
    echo
fi
exit 0
