#!/bin/bash

. /etc/eole/containers.conf

## SQUID ##
touch "$container_path_proxy/etc/squid/domaines_noauth_user"
touch "$container_path_proxy/etc/squid/domaines_nocache_user"
touch "$container_path_proxy/etc/squid/src_noauth_user"
touch "$container_path_proxy/etc/squid/src_nocache_user"
touch "$container_path_proxy/etc/squid/domaines_noauth_acad"
touch "$container_path_proxy/etc/squid/domaines_nocache_acad"
touch "$container_path_proxy/etc/squid/src_noauth_acad"
touch "$container_path_proxy/etc/squid/src_nocache_acad"
if [ ! -f "$container_path_proxy/etc/squid/src_noauth" ];then
    echo "127.0.0.1" > "$container_path_proxy/etc/squid/src_noauth"
fi
if [ ! -f "$container_path_proxy/etc/squid/src_nocache" ];then
    echo "127.0.0.1" > "$container_path_proxy/etc/squid/src_nocache"
fi

## DANSGUARDIAN ##
# /!\ ne pas supprimer /etc/dansguardian/languages /!\
rm -rf "$container_path_proxy/etc/dansguardian/dansguardian"*
rm -rf "$container_path_proxy/etc/dansguardian/authplugins"
rm -rf "$container_path_proxy/etc/dansguardian/contentscanners"
rm -rf "$container_path_proxy/etc/dansguardian/downloadmanagers"
rm -rf "$container_path_proxy/etc/dansguardian/lists"
# correction formatage des accents dansguardian (#502)
sed -i 's/\&ecute;/\&eacute;/g' "$container_path_proxy/etc/dansguardian/languages/french/messages"

danspath="/usr/share/eole/dansguardian"
# remplacement du script d'init (2 instances)
cp -f "$danspath/init/dansguardian" "$container_path_proxy/etc/init.d/dansguardian"
# mise à niveau de la configuration
$danspath/init_dans.py

exit 0
