#!/bin/bash

. /usr/share/eole/FonctionsEoleNg
. /etc/eole/containers.conf

## SQUID ##
touch "$container_path_proxy/etc/squid/domaines_noauth_user"
touch "$container_path_proxy/etc/squid/domaines_nocache_user"
touch "$container_path_proxy/etc/squid/src_noauth_user"
touch "$container_path_proxy/etc/squid/src_nocache_user"
touch "$container_path_proxy/etc/squid/domaines_noauth_acad"
touch "$container_path_proxy/etc/squid/domaines_nocache_acad"
touch "$container_path_proxy/etc/squid/src_noauth_acad"
touch "$container_path_proxy/etc/squid/src_nocache_acad"
if [ ! -f "$container_path_proxy/etc/squid/src_noauth" ];then
    echo "127.0.0.1" > "$container_path_proxy/etc/squid/src_noauth"
fi
if [ ! -f "$container_path_proxy/etc/squid/src_nocache" ];then
    echo "127.0.0.1" > "$container_path_proxy/etc/squid/src_nocache"
fi
if [ ! -f "$container_path_proxy/etc/squid/domaines_nopeerproxy" ];then
    echo "127.0.0.1" > "$container_path_proxy/etc/squid/domaines_nopeerproxy"
fi
# correction des droits sur winbindd_privileged (#699)
sed -i 's/chgrp winbindd_priv/chgrp proxy/g' "$container_path_proxy/etc/init.d/winbind"

## DANSGUARDIAN ##
# /!\ ne pas supprimer /etc/dansguardian/languages /!\
rm -rf "$container_path_proxy/etc/dansguardian/dansguardian"*
rm -rf "$container_path_proxy/etc/dansguardian/authplugins"
rm -rf "$container_path_proxy/etc/dansguardian/contentscanners"
rm -rf "$container_path_proxy/etc/dansguardian/downloadmanagers"
rm -rf "$container_path_proxy/etc/dansguardian/lists"
# correction formatage des accents dansguardian (#502)
sed -i 's/\&ecute;/\&eacute;/g' "$container_path_proxy/etc/dansguardian/languages/french/messages"

# FIXME : logs dans les conteneurs
RunCmd "chown -R proxy.proxy /var/log/dansguardian" proxy

danspath="/usr/share/eole/dansguardian"
# remplacement du script d'init (2 instances)
cp -f "$danspath/init/dansguardian" "$container_path_proxy/etc/init.d/dansguardian"
# mise à niveau de la configuration
$danspath/init_dans.py

# mise à disposition de lightsquid
if ! [ -d /var/www/html ];then
    mkdir -p /var/www/html
fi
ln -nsf /usr/share/lightsquid /var/www/html/
if ! [ -d /var/www/html/lightsquid/report ];then
    mkdir /var/www/html/lightsquid/report
fi

# gestion du démarrage de nmbd
upstart_conf=$container_path_proxy/etc/init/nmbd.conf
if [ -f $upstart_conf ]
then
    sed -i "s/^start on (local-filesystems and net-device-up IFACE!=lo)/start on runlevel [2345]/g" $upstart_conf
fi


exit 0
