#!/bin/sh

%if %%active_sarg == "oui"
if [ -x /usr/sbin/sarg-reports1 ]; then
  /usr/sbin/sarg-reports1 monthly
fi
if [ -x /usr/sbin/sarg-reports2 ]; then
  /usr/sbin/sarg-reports2 monthly
fi
%else
# SARG inactif
%end if
