#!/bin/bash
#########################################
# Surveillance du Reseau Virtuel Privé
#
# LB 10/01/2003 
# $Id: magic-rvp,v 1.1.1.1 2004/01/05 10:16:50 eole Exp $
#########################################

# Appel Bibliothèque
[ -x /usr/share/eole/FonctionsEoleNg ] || {
        echo "Pas de bibliotheque Eole !"
        exit 1
	}
. /usr/share/eole/FonctionsEoleNg
. ParseDico
rc=0
Init "RVP"
[ "$rc"  -ne '0' ] && {
                Zecho "Probleme Zephir"
		Zecho "RC = $rc"
		Zecho "Contacter l'administrateur"
		exit
	}

if [ ! -e /var/lock/rvp ]
then
# Le Service n'est pas actif!
# ON FAIT RIEN 
# car on se sait pas s'il doit être lancé ;-)
exit 2
fi
# Le Service est actif
# Est ce que le tunnel est en place ?

# test du Reseau/routeur
fping $adresse_ip_gw > /dev/null 2>&1 
if [ "$?" -ne 0 ]
then
	# Probleme Réseau
Zlog "Routeur $adresse_ip_gw ping HS"
else
Zlog "Routeur $adresse_ip_gw OK"
fi

# test du tunnel
/usr/share/eole/magic_rvp.py
RC="$?"
if [ "$RC" -ne 0 ]
then 
	# Non ;-(
	# On relance ...
	
Zlog "Probleme RVP detecte : $RC" 
Zlog "Un ou plusieurs Tunnels ont ete relances"
else
# C'est OK ;-)
# On Log
Zlog "Tunnel OK"
exit 0
fi
