#!/bin/bash
. /usr/share/eole/FonctionsEoleNg
. /usr/bin/ParseDico

EchoGras "*** Services Proxy"
# FIXME: squid tourne en 127.0.0.1
#TestService "proxy" $container_ip_proxy:8080
TestPid "proxy" squid
if [ $container_ip_proxy = '127.0.0.1' ];then
# sans conteneur
TestService "filtre web ($nom_machine_eth1)" $adresse_ip_eth1:3128
if [ $nombre_interfaces -gt 2 ]
then
   TestService "filtre web ($nom_machine_eth2)" $adresse_ip_eth2:3128
fi
else
# avec conteneurs (FIXME)
TestService "filtre web (conteneur)" $container_ip_proxy:3128
fi
echo
exit 0
