#!/bin/bash
. /usr/share/eole/FonctionsEoleNg
. /usr/bin/ParseDico

# test du RVP si configuré
EchoGras "*** Réseau virtuel privé"
if [ $install_rvp == 'oui' ];then
   if [ -x "/usr/share/eole/test-rvp" ];then
	printf ".  %${len_pf}s => " "RVP"
	/usr/share/eole/test-rvp 2>&1 >/dev/null
	if [ $? -eq 0 ];then
		EchoVert " Ok"
	else
		EchoRouge " Erreur"
	fi
   else
	NoConfig "RVP"
   fi
else
   Inactif "RVP"
fi
echo
exit 0
