#!/bin/sh
###############################################
## generation du rapport de logs du firewall
# samuel morin
# $Id: lance-fwlogwatch,v 1.1.1.1 2004/01/05 10:16:50 eole Exp $
##############################################
## generation du rapport de logs du firewall
/usr/sbin/fwlogwatch
sub=`date '+%d-%m-%y'` 
mv /var/www/ead/stats/fwlogwatch/fwlogwatch.html /var/www/ead/stats/fwlogwatch/${sub}.html

