#!/bin/bash
. /usr/share/eole/FonctionsEoleNg
. /usr/bin/ParseDico

if [ "$activer_revprox" == "oui" ];then
    EchoGras "*** Reverse Proxy"
    if [ -z $revprox_domainname ];then
        NoConfig "nginx"
    else
        TestHTTPPage "nginx" "http://localhost/50x.html"
    fi
    echo
fi
exit 0
