#!/bin/bash
. /usr/share/eole/FonctionsEoleNg
. /usr/bin/ParseDico

if [ "$activer_revprox" == "oui" ];then
    EchoGras "*** Reverse Proxy"
    if [ $revprox_auto_config_local_web = 'oui' -o $revprox_activate_http = 'oui' ];then
        TestHTTPPage "nginx" "http://localhost/50x.html"
    else
        NoConfig "nginx"
    fi
    echo
fi
exit 0
