#!/bin/bash

. /usr/share/eole/FonctionsEoleNg
. /usr/bin/ParseDico
tput bold
echo "*** Controle des interfaces"
tput sgr0
  Cpt=0;
  while [ $Cpt -lt $nombre_interfaces ]; do
	Var1="\$adresse_ip_eth$Cpt"
	if [ $Cpt -eq 0 ];then
	    Var2="\$nom_machine"
	else
	    Var2="\$nom_machine_eth$Cpt"
	fi
	eval TestIP $Var1 $Var2
	let Cpt=Cpt+1 
        done
tput bold
echo
echo "*** Controle de passerelle"
tput sgr0
TestIP $adresse_ip_gw "Defaut"
echo
exit 0
