#!/bin/bash
. /usr/share/eole/FonctionsEoleNg
. /usr/bin/ParseDico

EchoGras "*** Services Locaux"
TestService DNS localhost:53    	
TestService "Proxy"  127.0.0.1:8080    	
TestService "EAD2 " localhost:4201
TestService "Filtre Web ($nom_machine_eth1)" $adresse_ip_eth1:3128
if [ $nombre_interfaces -gt 2 ]
then
   TestService "Filtre Web ($nom_machine_eth2)" $adresse_ip_eth2:3128
fi
echo
Cpt=0;
while [ $Cpt -lt $nombre_interfaces ]; do
   Var1="\$adresse_ip_eth$Cpt"
   Var2="\$ssh_eth$Cpt"
   Eth="eth$Cpt"
   Adresse=`eval echo $Var1`
   Actif=`eval echo $Var2`
   if [  $Actif ==  "oui" ]
   then
	echo "Sur l'interface réseau $Eth"
	TestService "SSH" $Adresse:22    
	if [ $ead_web == 'oui' ];then
		TestService "EAD-Web" $Adresse:4200   
	else
		Inactif "EAD-Web"
	fi
   else
	echo "Sur l'interface réseau $Eth"
        Inactif "SSH"
        Inactif "EAD-Web"
   fi
   let Cpt=Cpt+1 
done
echo

# test du RVP si configuré
EchoGras "*** Réseau virtuel privé"
if [ $install_rvp == 'oui' -a -x "/usr/share/eole/test-rvp" ]
then
	printf ".  %20s => " "RVP"
	/usr/share/eole/test-rvp 2>&1 >/dev/null
	if [ $? -eq 0 ]
	then
		EchoVert " Ok"
	else
		EchoRouge " Erreur"
	fi
else
	Inactif "RVP"
fi
echo

EchoGras "*** Test des certificats"
if [ $active_nufw == 'oui' ] && [ ! $nuauth_tls_cert = '' ]; then
	TestCerts $nuauth_tls_cert 10 "certificat expiré"
fi
TestCerts /etc/ssl/certs/eole.crt 10 "certificat expiré"

exit 0
