#!/bin/bash
#
# chkconfig: 2345 85 15
# description: ipp2p is a program which detect and prevent P2P.
# processname: ipp2
# pidfile: /var/run/ipp2p.pid


RETVAL=0

. /lib/lsb/init-functions

prog="ipp2p"
module="ipt_ipp2p"
protocol="edk bit"

start() {
	log_begin_msg "Starting ipp2p"
        /sbin/modprobe $module
	/sbin/iptables -L -n |grep ipp2p >/dev/null
	if [ $? == "0" ]
	then
	for i in $procotol; do
		/sbin/iptables -D FORWARD -m limit --limit 12/min -m ipp2p --$i -j ULOG --ulog-prefix "IPP2P-$i-LOG"
		/sbin/iptables -D FORWARD -m ipp2p --$i -j DROP
	done
		echo
		rm -f /var/lock/ipp2p
	fi
	for i in $protocol; do
	/sbin/iptables -I FORWARD 1 -m limit --limit 12/min -m ipp2p --$i -j ULOG --ulog-prefix "IPP2P-$i-LOG"
	/sbin/iptables -I FORWARD 2 -m ipp2p --$i -j DROP
	done
	RETVAL=$?
	log_end_msg $RETVAL
	[ $RETVAL -eq 0 ] && touch /var/lock/ipp2p
	return $RETVAL

}

stop() {
	log_begin_msg "Stop ipp2p"
for i in $protocol; do
	/sbin/iptables -D FORWARD -m limit --limit 12/min -m ipp2p --$i -j ULOG --ulog-prefix "IPP2P-$i-LOG"
	/sbin/iptables -D FORWARD -m ipp2p --$i -j DROP
done
        /sbin/rmmod $module
	RETVAL=$?
	log_end_msg $RETVAL
	echo
	[ $RETVAL -eq 0 ] && rm -f /var/lock/ipp2p
	return $RETVAL
}

case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  restart|reload)
	/sbin/iptables -L -n |grep ipp2p >/dev/null
	if [ $? == "0" ]
	then
        	stop
	fi
        start
        RETVAL=$?
        ;;
  condrestart)
        if [ -f /var/lock/ipp2p ]; then
            stop
            start
            RETVAL=$?
        fi
        ;;
  status)
  	/sbin/iptables -L -n |grep "ipp2p"
        RETVAL=$?
        ;;
  *)
        gprintf "Usage: %s {start|stop|restart|condrestart|status}\n" "$0"
        exit 1
esac

exit $RETVAL
