#!/bin/bash
#
# killp2p          Start/Stop le filtrage p2p
#
# chkconfig: 2345 35 60
# description:  lance p2p si activé depuis l'ead
# $Id
# config:

. /lib/lsb/init-functions

PROG="l7filter"
DAEMON=/etc/init.d/$PROG

if [ -f /var/lib/eole/config/killp2p.conf ];then
    # définit la variable $KILLP2P
    . /var/lib/eole/config/killp2p.conf
fi

start() {
        if [ "$KILLP2P" == "on" ]
        then
                $DAEMON start
                #log_begin_msg "Lancement du filtrage P2P ($PROG): "
                #$DAEMON start >/dev/null 2>&1
                #RETVAL=$?
                #log_end_msg $RETVAL
        else
                echo "Le filtrage P2P est désactivé"
                exit 0
        fi
}

stop() {
        if [ "$KILLP2P" == "on" ];then
            $DAEMON stop 2>/dev/null
        else
            $DAEMON stop &>/dev/null
        fi
}

status() {
        if [ "$KILLP2P" == "on" ];then
            $DAEMON status
        else
            echo "Le filtrage P2P est désactivé"
            exit 1
        fi
}

case "$1" in
  start)
          start
        ;;
  stop)
          stop
        ;;
  restart)
          stop
          start
        ;;
  reload)
          restart
        ;;
  status)
          status
        ;;
  *)
        echo "Usage: $0 {start|stop|status|reload|restart}"
        exit 1
esac
