#!/bin/bash
#
# chkconfig: 2345 85 15
# description: l7filter is a program which detect and prevent some protocols
# processname: l7filter
# pidfile: /var/run/l7filter.pid

. /lib/lsb/init-functions

module="xt_layer7"
protocol="bittorrent edonkey"

clean() {
    # nettoyage iptables
    for i in $protocol; do
        /sbin/iptables -t mangle -D POSTROUTING -m layer7 --l7dir /etc/l7-protocols/protocols --l7proto $i
        /sbin/iptables -D FORWARD -m limit --limit 12/min -m layer7 --l7proto $i -j LOG --log-prefix "L7FILTER-$i-LOG"
        /sbin/iptables -D FORWARD -m layer7 --l7dir /etc/l7-protocols/protocols --l7proto $i -j DROP
    done
    /sbin/iptables -D FORWARD -p udp --dport 123 -j ACCEPT
    /sbin/iptables -D FORWARD -p udp --sport 123 -j ACCEPT
}

start() {
    log_begin_msg "Starting l7filter"
    /sbin/iptables -L -n |grep -q l7proto
    if [ $? == "0" ];then
        clean
        rm -f /var/lock/layer7
    fi
    for i in $protocol; do
        /sbin/iptables -t mangle -A POSTROUTING -m layer7 --l7dir /etc/l7-protocols/protocols --l7proto $i
        /sbin/iptables -I FORWARD 2 -m limit --limit 12/min -m layer7 --l7proto $i -j LOG --log-prefix "L7FILTER-$i-LOG"
        /sbin/iptables -I FORWARD 3 -m layer7 --l7dir /etc/l7-protocols/protocols --l7proto $i -j DROP
    done
    /sbin/iptables -I FORWARD 1 -p udp --dport 123 -j ACCEPT
    /sbin/iptables -I FORWARD 1 -p udp --sport 123 -j ACCEPT
    RETVAL=$?
    [ $RETVAL -eq 0 ] && touch /var/lock/layer7
    log_end_msg $RETVAL
}

stop() {
    log_begin_msg "Stop l7filter"
    clean
    RETVAL=$?
    rm -f /var/lock/layer7
    log_end_msg $RETVAL
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart|reload)
        /sbin/iptables -L -n |grep -q l7proto
        if [ $? == "0" ];then
            stop
        fi
        start
        RETVAL=$?
        ;;
    condrestart)
        if [ -f /var/lock/layer7 ]; then
            stop
            start
            RETVAL=$?
        fi
        ;;
    status)
        /sbin/iptables -L -n |grep -q l7proto
        exit $?
        ;;
    *)
        echo "Usage: $0 {start|stop|restart|condrestart|status}"
        exit 1
esac
